### PR TITLE
LittleFS 2.8.1

### PR DESCRIPTION
**Pull request by deadprogram**
This PR updates TinyFS to use LittleFS 2.8.1

Addresses https://github.com/tinygo-org/tinyfs/issues/13

### CODE REVIEW

**Comment by deadprogram** [comment]
@trichner please take a look.

**Comment by bgould** [comment]
Looks good to me ... looks like there could be some new options too that could useful to wrap with the Go API (in a separate PR), such as LFS_THREADSAFE and https://github.com/tinygo-org/tinyfs/pull/14/files#diff-d0b688889286d2d437e32f03926e02147d1ad54db1467efad1e0059fa20ccec1R696

**Review by bgould — APPROVED** [review]

**Comment by deadprogram** [comment]
Thanks for quick review @bgould now merging.

**Comment by trichner** [comment]
> @trichner please take a look.

Great stuff! Thanks!
I'll give it a go.

**Comment by trichner** [comment]
Alright, it works as it should. There are some issues together with littlefs-fuse though, unclear what part (drivers/sdcard, tinyfs/littlefs or littlefs-fuse) is responsible tough.

Devices formatted with tinyfs/littlefs do not mount successfully with littlefs-fuse because the expected block count does not match.

drivers/sdcard reports:
```
write block size: 512
erase block size: 512
size: 15931015168
block count: 31115264
```

whereas Linux reports:
```
cat /sys/block/sda/size
31116288
```

which leads to
```
sudo ./lfs --stat /dev/sda
littlefs/lfs.c:4448:error: Invalid block count (31115264 != 31116288)
lfs_fuse.c:644:error: Invalid argument
```

The workaround is to explicitly pass the block count:
```
sudo ./lfs --block_count=31115264 --stat /dev/sda
```

I'm wondering though where the `31116288 - 31115264 = 1024 blocks` dissappear when using `drivers/sdcard`.

**Comment by deadprogram** [comment]
> I'm wondering though where the 31116288 - 31115264 = 1024 blocks dissappear when using drivers/sdcard

Sounds a lot like an off by one error?

**Comment by deadprogram** [comment]
It would probably have to be an off by 2 error, from looking at https://github.com/tinygo-org/drivers/blob/dev/sdcard/sdcard.go#L625

**Comment by trichner** [comment]
Thanks for checking it out!

First off: I don't think its caused by the upgrade here, but rather that the newer littlefs got a bit more restrictive.

That was my thinking as well, tinyfs/littlefs takes the size from here\
https://github.com/tinygo-org/drivers/blob/fd21e6ac9b4a5c3bd906ed8a82783a972be6d4ca/sdcard/csd.go#L104
to set up the config here
https://github.com/tinygo-org/tinyfs/blob/5ec6806173612cb453b3eab5974264eeef3b011d/littlefs/go_lfs.go#L171

Which looks reasonable to me.

Since its off by a multiple of 512 it should also not be caused by the division there or something similar.


On a side note, its also not obvious to me why littlefs would enforce that the hardware size matches the one in the superblock. As long as its smaller than the harware size that should be fine in my naive view :)

**Pull request merged**
